// This file is automatically generated by vscode-react-native@0.3.2
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/alejandro.ledesma/workspace/react/alejandroledesma-react-native/node_modules/react');
var {Component} = React;

var ReactNative = require('/Users/alejandro.ledesma/workspace/react/alejandroledesma-react-native/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('/Users/alejandro.ledesma/workspace/react/alejandroledesma-react-native/index.ios.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('alejandro-ledesma-react-native', appParameters);
});